---

- hosts: tezos-remote-signer
  become: true
  roles:
  - tezos-remote-signer
  - ansible-node-exporter
  vars:
      gke_signer_endpoint_hostname: <insert here hostname of remote signer ssh endpoint>
      gke_signer_endpoint_port: <insert here port of remote signer ssh endpoint>
      tezos_version: master
