---
# handlers file for tezos-remote-signer

- name: Restart ssh
  service:
    name: ssh
    state: restarted

- name: Restart ufw
  service:
    name: ufw
    state: restarted

- name: Restart network-manager
  service:
    name: network-manager
    state: restarted

- name: Reload resolvconf
  command: resolvconf -u
